name: Ktlint

on:
  pull_request:
    branches-ignore:
      - dependabot/*

jobs:
  Ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: "Install ktlint"
        uses: nbadal/action-ktlint-setup@v1
        with:
          ktlint_version: '1.2.1'
      - run: ktlint
        shell: bash